const { cmd } = require("../command");
const axios = require("axios");

cmd({
  pattern: "aiimg",
  react: "🚀",
  desc: "Generate multiple images using AI.",
  category: "main",
  filename: __filename
}, async (conn, mek, m, { q, reply }) => {
  try {
    if (!q) return reply("Please provide a prompt for the image.");

    await reply("> *CREATING IMAGES ...🔥*");

    const apiUrl = `https://api-aswin-sparky.koyeb.app/api/search/imageai?search=${encodeURIComponent(q)}`;

    const response = await axios.get(apiUrl);

    if (!response || !response.data || !response.data.data || !response.data.data.length) {
      return reply("Error: The API did not return any images. Try again later.");
    }

    const images = response.data.data;

    // Send each image one by one
    for (const imageUrl of images) {
      await conn.sendMessage(m.chat, {
        image: { url: imageUrl },
        caption: `💸 *Imagine Generated By 𝙳𝙰𝚁𝙺-𝙺𝙽𝙸𝙶𝙷𝚃-𝚇𝙼𝙳* 🚀\n✨ Prompt: *${q}*`
      });
    }

  } catch (error) {
    console.error("AiImage Error:", error);
    reply(`An error occurred: ${error.response?.data?.message || error.message || "Unknown error"}`);
  }
});
